name: Release Docker Image
 
 
on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]
 
 
env:
  DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
  DOCKER_IMAGE_NAME: ms-test
  TOKEN: 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
 
 
jobs:
  docker:
    name: CI Release
    runs-on: ubuntu-latest
 
 
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --tag $DOCKER_HUB_USER/$DOCKER_IMAGE_NAME:$GITHUB_RUN_NUMBER .
    - name: Login to Docker Hub
      run: docker login --username ${{ secrets.DOCKER_HUB_USER }} --password ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Push the docker image
      run: docker push $DOCKER_HUB_USER/$DOCKER_IMAGE_NAME:$GITHUB_RUN_NUMBER
 
  merge-branch:
    name: Merge to master
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge dev -> master
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: master
          github_token: ${{ secrets.TOKEN  }}
          #github_token: ${{ github.token }}
          # github_token: ${{ secrets.GH_PAT ccc dddd}}
          # github_token: ${{ secrets.GITHUB_TOKEN }}
 